# Google 股價為範例，操作時間序列的技巧

In [4]:
import pandas as pd
import datetime as dt
import pandas_datareader.data as data

start = dt.datetime(2020, 3, 1)
end = dt.datetime(2020, 4, 30)
df = data.get_data_yahoo('GOOG', start, end)
df

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2020-03-02,1390.869995,1326.814941,1351.609985,1389.109985,2431500,1389.109985
2020-03-03,1410.150024,1332.000000,1399.420044,1341.390015,2402300,1341.390015
2020-03-04,1388.089966,1343.109985,1359.229980,1386.520020,1913300,1386.520020
2020-03-05,1358.910034,1305.099976,1350.199951,1319.040039,2561300,1319.040039
2020-03-06,1306.219971,1261.050049,1277.060059,1298.410034,2660600,1298.410034
2020-03-09,1254.760010,1200.000000,1205.300049,1215.560059,3365400,1215.560059
2020-03-10,1281.150024,1218.770020,1260.000000,1280.390015,2611400,1280.390015
2020-03-11,1260.959961,1196.069946,1249.699951,1215.410034,2608500,1215.410034
2020-03-12,1193.869995,1113.300049,1126.000000,1114.910034,4226700,1114.910034
2020-03-13,1219.760010,1117.142944,1179.000000,1219.729980,3700100,1219.729980
2020-03-16,1152.266968,1074.439941,1096.000000,1084.329956,4252400,1084.329956
2020-03-17,1130.859985,1056.010010,1093.109985,1119.800049,3861500,1119.800049
2020-03-18,1106.500000,1037.280029,1056.510010,1096.800049,4233400,1096.800049
2020-03-19,1157.969971,1060.108032,1093.050049,1115.290039,3651100,1115.290039
2020-03-20,1143.989990,1065.489990,1135.719971,1072.319946,3601800,1072.319946
2020-03-23,1071.319946,1013.536011,1061.319946,1056.619995,4044100,1056.619995
2020-03-24,1135.000000,1090.619995,1103.770020,1134.459961,3344500,1134.459961
2020-03-25,1148.900024,1086.010010,1126.469971,1102.489990,4081500,1102.489990
2020-03-26,1169.969971,1093.530029,1111.800049,1161.750000,3571700,1161.750000
2020-03-27,1150.670044,1105.910034,1125.670044,1110.709961,3208500,1110.709961
2020-03-30,1151.630005,1096.479980,1125.040039,1146.819946,2574100,1146.819946
2020-03-31,1175.310059,1138.140015,1147.300049,1162.810059,2486400,1162.810059
2020-04-01,1129.689941,1097.449951,1122.000000,1105.619995,2344200,1105.619995
2020-04-02,1126.859985,1096.400024,1098.260010,1120.839966,1964900,1120.839966
2020-04-03,1123.540039,1079.810059,1119.015015,1097.880005,2313400,1097.880005
2020-04-06,1194.660034,1130.939941,1138.000000,1186.920044,2664700,1186.920044
2020-04-07,1225.000000,1182.229980,1221.000000,1186.510010,2387300,1186.510010
2020-04-08,1219.069946,1188.160034,1206.500000,1210.280029,1975100,1210.280029
2020-04-09,1225.569946,1196.734985,1224.079956,1211.449951,2175400,1211.449951
2020-04-13,1220.510010,1187.598022,1209.180054,1217.560059,1739800,1217.560059
2020-04-14,1282.069946,1236.930054,1245.089966,1269.229980,2470400,1269.229980
2020-04-15,1280.459961,1240.400024,1245.609985,1262.469971,1671700,1262.469971
2020-04-16,1279.000000,1242.619995,1274.099976,1263.469971,2518100,1263.469971
2020-04-17,1294.430054,1271.229980,1284.849976,1283.250000,1949000,1283.250000
2020-04-20,1281.599976,1261.369995,1271.000000,1266.609985,1695500,1266.609985
2020-04-21,1254.270020,1209.709961,1247.000000,1216.339966,2153000,1216.339966
2020-04-22,1285.613037,1242.000000,1245.540039,1263.209961,2092400,1263.209961
2020-04-23,1293.310059,1265.670044,1271.550049,1276.310059,1566200,1276.310059
2020-04-24,1280.400024,1249.449951,1261.170044,1279.310059,1639600,1279.310059
2020-04-27,1296.150024,1269.000000,1296.000000,1275.880005,1600600,1275.880005
2020-04-28,1288.050049,1232.199951,1287.930054,1233.670044,2951300,1233.670044
2020-04-29,1359.989990,1325.339966,1341.459961,1341.479980,3793600,1341.479980
2020-04-30,1352.819946,1322.489990,1324.880005,1348.660034,2668900,1348.660034

## DatetimeIndex
用時間作為索引的型態<br>
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.html

In [12]:
df.index.week

Int64Index([10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 13, 13,
            13, 13, 13, 14, 14, 14, 14, 14, 15, 15, 15, 15, 16, 16, 16, 16, 16,
            17, 17, 17, 17, 17, 18, 18, 18, 18],
           dtype='int64', name='Date')

## 計算每週交易量總和

In [13]:
df['week'] = df.index.week
df

,High,Low,Open,Close,Volume,Adj Close,week
Date,,,,,,,
2020-03-02,1390.869995,1326.814941,1351.609985,1389.109985,2431500,1389.109985,10
2020-03-03,1410.150024,1332.000000,1399.420044,1341.390015,2402300,1341.390015,10
2020-03-04,1388.089966,1343.109985,1359.229980,1386.520020,1913300,1386.520020,10
2020-03-05,1358.910034,1305.099976,1350.199951,1319.040039,2561300,1319.040039,10
2020-03-06,1306.219971,1261.050049,1277.060059,1298.410034,2660600,1298.410034,10
2020-03-09,1254.760010,1200.000000,1205.300049,1215.560059,3365400,1215.560059,11
2020-03-10,1281.150024,1218.770020,1260.000000,1280.390015,2611400,1280.390015,11
2020-03-11,1260.959961,1196.069946,1249.699951,1215.410034,2608500,1215.410034,11
2020-03-12,1193.869995,1113.300049,1126.000000,1114.910034,4226700,1114.910034,11
2020-03-13,1219.760010,1117.142944,1179.000000,1219.729980,3700100,1219.729980,11
2020-03-16,1152.266968,1074.439941,1096.000000,1084.329956,4252400,1084.329956,12
2020-03-17,1130.859985,1056.010010,1093.109985,1119.800049,3861500,1119.800049,12
2020-03-18,1106.500000,1037.280029,1056.510010,1096.800049,4233400,1096.800049,12
2020-03-19,1157.969971,1060.108032,1093.050049,1115.290039,3651100,1115.290039,12
2020-03-20,1143.989990,1065.489990,1135.719971,1072.319946,3601800,1072.319946,12
2020-03-23,1071.319946,1013.536011,1061.319946,1056.619995,4044100,1056.619995,13
2020-03-24,1135.000000,1090.619995,1103.770020,1134.459961,3344500,1134.459961,13
2020-03-25,1148.900024,1086.010010,1126.469971,1102.489990,4081500,1102.489990,13
2020-03-26,1169.969971,1093.530029,1111.800049,1161.750000,3571700,1161.750000,13
2020-03-27,1150.670044,1105.910034,1125.670044,1110.709961,3208500,1110.709961,13
2020-03-30,1151.630005,1096.479980,1125.040039,1146.819946,2574100,1146.819946,14
2020-03-31,1175.310059,1138.140015,1147.300049,1162.810059,2486400,1162.810059,14
2020-04-01,1129.689941,1097.449951,1122.000000,1105.619995,2344200,1105.619995,14
2020-04-02,1126.859985,1096.400024,1098.260010,1120.839966,1964900,1120.839966,14
2020-04-03,1123.540039,1079.810059,1119.015015,1097.880005,2313400,1097.880005,14
2020-04-06,1194.660034,1130.939941,1138.000000,1186.920044,2664700,1186.920044,15
2020-04-07,1225.000000,1182.229980,1221.000000,1186.510010,2387300,1186.510010,15
2020-04-08,1219.069946,1188.160034,1206.500000,1210.280029,1975100,1210.280029,15
2020-04-09,1225.569946,1196.734985,1224.079956,1211.449951,2175400,1211.449951,15
2020-04-13,1220.510010,1187.598022,1209.180054,1217.560059,1739800,1217.560059,16
2020-04-14,1282.069946,1236.930054,1245.089966,1269.229980,2470400,1269.229980,16
2020-04-15,1280.459961,1240.400024,1245.609985,1262.469971,1671700,1262.469971,16
2020-04-16,1279.000000,1242.619995,1274.099976,1263.469971,2518100,1263.469971,16
2020-04-17,1294.430054,1271.229980,1284.849976,1283.250000,1949000,1283.250000,16
2020-04-20,1281.599976,1261.369995,1271.000000,1266.609985,1695500,1266.609985,17
2020-04-21,1254.270020,1209.709961,1247.000000,1216.339966,2153000,1216.339966,17
2020-04-22,1285.613037,1242.000000,1245.540039,1263.209961,2093100,1263.209961,17
2020-04-23,1293.310059,1265.670044,1271.550049,1276.310059,1566200,1276.310059,17
2020-04-24,1280.400024,1249.449951,1261.170044,1279.310059,1640400,1279.310059,17
2020-04-27,1296.150024,1269.000000,1296.000000,1275.880005,1600600,1275.880005,18
2020-04-28,1288.050049,1232.199951,1287.930054,1233.670044,2951300,1233.670044,18
2020-04-29,1359.989990,1325.339966,1341.459961,1341.479980,3793600,1341.479980,18
2020-04-30,1352.819946,1322.489990,1324.880005,1348.660034,2665400,1348.660034,18

In [14]:
df.groupby('week').Volume.sum()

week
10    11969000
11    16512100
12    19600200
13    18250300
14    11683000
15     9202500
16    10349000
17     9148200
18    11010900
Name: Volume, dtype: int64

## resample
調整週期重新採樣的方法<br>
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html#pandas.DataFrame.resample

In [15]:
ten = df.resample('10D').mean()
ten

,High,Low,Open,Close,Volume,Adj Close,week
Date,,,,,,,
2020-03-02,1331.388748,1272.864365,1306.565002,1305.728775,2.569288e+06,1305.728775,10.375000
2020-03-12,1157.888131,1074.824428,1111.341431,1117.597151,3.932429e+06,1117.597151,11.714286
2020-03-22,1143.257150,1089.175153,1114.481445,1125.094273,3.330114e+06,1125.094273,13.285714
2020-04-01,1177.769985,1138.817854,1161.264997,1159.928571,2.260714e+06,1159.928571,14.571429
2020-04-11,1273.011658,1240.024679,1254.971659,1260.431661,2.007417e+06,1260.431661,16.166667
2020-04-21,1301.325394,1264.482483,1284.441269,1279.357513,2.307950e+06,1279.357513,17.500000